xaptum/xtt

- CMakeLists.txt
- test/full_handshake-test-tpm.c
In tests, we need to make sure to "finalize" the SAPI and TCTI (TPM TSS stuff) contexts, so that we properly close the TCP connection to the TPM, especially if it's the TPM simulator.
> Fix sapi ctx cleanup

- CMakeLists.txt
- examples/xtt_client.c
The examples weren't initializing the `crypto` sub system (i.e. libsodium).
> Initialize crypto examples

- CMakeLists.txt
- include/xtt/crypto_wrapper.h
- src/libsodium_wrapper.c
Our `xtt_ed25519_priv_key` type is actually libsodium's private key type, which caches some of the private key operations. Libsodium has a function for extracting the actual private key from this structure, so this patch adds a wrapper for this to `xtt/crypto_wrapper.h`
> Extract private key for Ed25519

- CMakeLists.txt
- include/xtt/crypto_types.h
- src/crypto_types.c
Also adds a conversion function for going from identity_type -> string.
This does not add a conversion for going the other way, string -> identity_type.
That is a bit more fraught, and doesn't seem necessary right now.
> Add a c-string version of `xtt_identity_type`

- debian/control
The `xtt` public headers `#include` headers from `xaptum-tpm`, so the `libxtt-dev` package needs to depend on `libxaptum-tpm-dev`.
> Make dev package depend on xaptum-tpm dev package

- examples/xtt_client.c
- include/xtt/asn1_utilities.h
- src/asn1_utilities.c
- util/xtt_wrap_keys_as_ASN1.c
This series improves portability and safety of the asn1 utility functions.
- Exports the certificate length macros as functions for use by wrapper libraries
- Explicitly validates the length of the output buffers for x509 and ASN1 encodings.
> Asn1 safety and portability

- examples/xtt_generate_certificate.c
- include/xtt/certificates.h
- src/certificates.c
- test/full_handshake-test-software.c
- test/full_handshake-test-tpm.c
> Add a missing `xtt_` prefix to `generate_server_certificate_ed25519`

- CMakeLists.txt
If `USE_TPM` is off, we shouldn't require the `TPM` component of `ecdaa`.
> Fix ecdaa-tpm requirement

- src/libsodium_wrapper.c
On some older versions of Linux `linux/random.h` refers to types
defined in `linux/types.h`, but fails to `#include` it. So, we include
it ourselves.
> Fix imports for older Linux versions

- src/internal/asn1.c
ASN.1 DER type INTEGER (which we use for serial number in certificate) is expected to be:
- A positive number, with the most-significant bit equal to 0
- A twos-complement negative number, with the most-significant bit equal to 1
- A positive number, with the most-significant BYTE equal to 0, and the 9th-most-significant bit equal to 1
We were forcing the most-significant byte to 0, which indicates that the 9th-bit would be 1, but we weren't demanding that. This caused problems with some parsers.
The fix is to set just the most-significant-BIT to 0.
> ASN1: Set most-significant-BIT (not byte) to 0 in INTEGER

- CMakeLists.txt
This is to avoid polluting the global variables
> Set compiler flags (e.g. -std= and -Werror) as add_compile_options.

- CMakeLists.txt
Otherwise CMake looks for both C and C++ compilers, but some embedded environments may not have a C++ compiler available.
> cmake: explicitly set language as C

- README.md
- examples/CMakeLists.txt
- examples/xtt_client.c
This series updates the `xtt_client` example in the following ways:
- Uses the most-recent changes to `xdaa-issuer`'s issuing of basename and server_id to TPM, in order to read these data from the TPM, rather than from file
- Converts CLI parameter parsing from hand-rolled to using `getopts`
- The `getopts` param handling now allows the TPM TCTI device file to be set from the CLI (and thus this PR fixes #37)
- The `getopts` param handling also allows setting the requested client ID from the CLI, not from file (and the default is to use `null_id`)
Nb. If not using a TPM, files are of course still required, and their locations are still hard-coded in the executable. Also, this does not update the `xtt_server` in similar ways.
> Allow the client to read everything from TPM, and require no external files

- examples/xtt_server.c
- include/xtt/crypto_wrapper.h
- src/ecdaa_wrapper.c
- src/libsodium_wrapper.c
Rather than cast the `xtt_crypto_get_random` function to the type `ecdaa_rand_func`, create a wrapper function to ensure the signatures are the same and handle any possible conversion problems.
As part of this change, we're also no longer returning `int` from `xtt_crypto_get_random`, and instead returning `void`. The function that `xtt_crypto_get_random` wraps returns `void` anyhow, so this return type is misleading and shouldn't be checked (which it, largely, wasn't in the existing  code).
Fixes #42
> Fix invalid random function casts in ecdaa wrapper

- examples/xtt_client.c
This PR add the following to the `xtt_client`:
- Use `xtt_strerror` for printing errors to stdout
- Use `getaddrinfo` for DNS-resolution of server hostnames in
- Don't buffer `stdout` output, so regular output doesn't come out after the `stderr` reporting
> Client: Use DNS for server hostname

- include/xtt/crypto_wrapper.h
- src/internal/crypto_utils.c
- test/certificate_test.c
- test/wrapper_sanity-test.c
Removed #include's related to AMCL from public API since AMCL uses macros that are exclusive to C. When we try to compile in C++, the macros are undefined. However, we can get around this by only using AMCL in the XTT library that is compiled in C.
> Fixing ECDSA for CPP

- examples/xtt_client.c
- examples/xtt_server.c
In the example client and server, define the GID to be SHA-256(GPK | basename), rather than just of the GPK.
> Examples: Include basename in GID computation

- include/xtt/crypto_types.h
- include/xtt/util/asn1.h
- src/crypto_types.c
- src/util/internal/asn1.c
- src/util/internal/asn1.h
Fixes #55 by inserting `:` every 4 characters. While not a true IPv6 format, much more readable than a string of hex digits.
> Put common name in IPv6 formatting

- tool/parse_cli.c
-Usage string will now print exactly what the user enters. This will be helpful when the naming eventually changes.
-Fixes #62
> Standardize usage string

- include/xtt/util/util_errors.h
- src/util/file_io.c
- tool/CMakeLists.txt
- tool/infocert.c
- tool/infocert.h
- tool/parse_cli.c
- tool/xtt.c
`infocert` parses the certificate depending on what type we input. It takes the raw hex and prints out the important information to the screen-no files are created.
> Add tool capability to parse certificates

- tool/parse_cli.c
- tool/xtt.c
Fixes #66 Instead of printing out error messages to the screen or file, print error messages as stderror's.
> Change error messages to stderror

- tool/client.c
The client code in the tool was using a hardcoded length for the basename of 8 bytes (which is the length of the example basename). The `xtt_read_from_file` function allows unknown-length file reads, so we need to use that (just as is done in the server code).
> tool: Don't hardcode basename length in client.c

- CMakeLists.txt
- examples/xtt_client.c
- include/xtt/tpm/handles.h
- src/tpm/handles.c
- tool/client.c
Instead of having to set the handles' values with each handshake, we have put them in a header file that sets a `#define` for each of the handles that we use.
Fixes #73.
> Add Standardized TPM handles

- examples/xtt_client.c
- tool/client.c
`ifdef`-ed out functions that were only to be used with TPM support.
Fixes #82
> Fix tool to build without TPM support

- .travis.yml
- .travis/install-amcl.sh
- .travis/install-ecdaa.sh
- .travis/install-libsodium.sh
- .travis/install-xaptum-tpm.sh
- pin the dependency version to fix the travis build
- DRY up travis.yml by specifying a build matrix
> travis: pin ecdaa to a specific version

- tool/parse_cli.c
`server_id` was a requirement of both the client and genservercert. In order to get rid of `server_id.bin`, I changed the client code to accept the `server_cert` as input and find the randomly generated server_id from the server's certificate.
Fixes #81
> Fixing inconsistencies in the XTT tool

- include/xtt/tpm/handles.h
- src/tpm/handles.c
- tool/client.c
Changes the client code to only read in a root cert file while using software DAA. If using the TPM, this will read in an `xtt_root_certificate` from the TPM itself. Adds a TPM handle for the root certificate.
Fixes #95
> tool: read root cert fix

- include/xtt/util/root.h
- src/util/root.c
- tool/parse_cli.c
- tool/xtt.c
Generating a root certificate used to require a private key, which is unnecessary. Each part of the tool is not independent, so there is no need to create a key pair within genrootcert.
> tool: remove priv key from genrootcert

- .travis.yml
Fixes #102 and removes `-DBUILD_EXAMPLES` since the examples directory does not exist anymore.
> Travis add builds for static libs and install

- .travis.yml
- CMakeLists.txt
- README.md
This adds Dev and DevDebug build types, which use `-Werror`, to Travis-CI and removes `-Werror` from the Release, RelWithDebInfo, and Debug builds.
Fixes #69
> Remove -Werror from all builds but dev

- .travis.yml
- CMakeLists.txt
The use of xaptum-tpm's new NVRAM functionality requires we use v0.5.7 or greater, not 0.5.6.
fixes #104
> cmake: Require xaptum-tpm v0.5.7 or higher.

- CMakeLists.txt
- include/xtt.h
- include/xtt/tpm/context.h
- include/xtt/tpm/nvram.h
- src/tpm/context.c
- src/tpm/nvram.c
- tool/client.c
- tool/parse_cli.c
- tool/parse_cli.h
- tool/read_nvram.c
- tool/read_nvram.h
- tool/xtt.c
This series:
- Moves the TPM context files from under the `util` namespace into the `tpm` namespace
- Moves the TPM context buffers (the raw memory for the TCTI/SAPI contexts) into the TPM context, and uses that structure to manage the memory (via `init` and `free` functions for the `xtt_tpm_context` object)
- Includes `USE_TPM` in more parts of the tool, to ensure the tool still builds even with `USE_TPM=OFF` (and that its help messages are still helpful in that case, too)
> Re-organize TPM context structure

- include/xtt/crypto/kx.h
- include/xtt/crypto_wrapper.h
- src/libsodium_wrapper.c
- test/CMakeLists.txt
- test/cpp/CMakeLists.txt
- test/cpp/cpp_test.cpp
Because `public` is a reserved keyword in C++, we can't use that as an identifier in our public API (because we want that to be include-able in C++ projects).
This series:
- Renames the few places where `public` was used to `public_key`
- Adds a simple test executable whose purpose is to be compiled by a C++ compiler, to check that this compilation works
> Rename `public` in API, so C++ compilers won't complain

- include/xtt/util/file_io.h
- src/util/asn1.c
- src/util/file_io.c
- src/util/generate_server_certificate.c
- src/util/generate_x509_certificate.c
- src/util/root.c
- tool/client.c
- tool/read_nvram.c
Set permissions for created files, especially for the longterm certificate and private key.
Right now, the files that the tool creates also follow these permissions and files that are created when reading in from the TPM's nvram currently gives anything it reads the same permissions as a certificate (0644).
Fixes #114
> Add permission to `xtt_save_to_file`

- src/util/file_io.c
This patch adds the `O_TRUNC` flag to the `open` call in `util/file_io.c`, so that any existing contents of a file will be deleted before writing the new output.
Fixes #117
> util: Delete any existing contents of file before writing output.

- test/CMakeLists.txt
This became a problem when using this downstream in the `xmb` project (which sets `BUILD_TOOL=OFF`, and thus then has its tests fail because the tool_test fails).
> test: Only run "tool_test" if BUILD_TOOL=ON.

- include/xtt/context.h
- include/xtt/crypto/hmac.h
- include/xtt/crypto_wrapper.h
- include/xtt/util/asn1.h
- src/context.c
- src/internal/crypto_utils.c
- src/internal/crypto_utils.h
- src/libsodium_wrapper.c
- src/util/asn1.c
- tool/client.c
- tool/parse_cli.c
This PR implements the TPM key storage discussed in Issue #120. The implementation here is largely that described in that issue, except that no TPM-related functions are added to `crypto_wrapper.h`; this is because the "higher-level" functions have already been provided by the new xaptum-tpm API (and I didn't see a need to provide the "wrapper" implementation-agility for xaptum-tpm that we have for the other crypto libraries).
This work also includes:
- Bringing back SHA-256 hashing in the `crypto` sub-library
- This is needed for creating TPM ECDSA signature, though it won't be used as a hash function for the handshake
- Updating the X.509 certificate generation to allow signing using a TPM key
- My plan had been to actually rip out the X.509 stuff, but it seemed less problematic to just …
> Store longterm key in TPM
